rm(list = ls())
library(spliceR)
cuffDB <- readCufflinks(dir='/Users/2kisa/Dr.Shen_challenge/diff_out/', rebuild=TRUE,gtfFile='/Users/2kisa/Dr.Shen_challenge/merged.gtf', genome='poplar')
cuffDB_spliceR <- prepareCuff(cuffDB,removeNonChanonicalChr=FALSE)
mySpliceRList<-spliceR(cuffDB_spliceR, compareTo='preTranscript', filters=c('expressedGenes','geneOK', 'isoOK', 'expressedIso','isoClass'), expressionCutoff=0, useProgressBar=T)
myTranscripts <- transcripts(cuffDB_spliceR)
myExons <- exons(cuffDB_spliceR)
conditions(cuffDB_spliceR)
myplot1<- spliceRPlot(mySpliceRList, evaluate="nr_AS", asType="ESI")
totalNumberOfAS(myplot1)
